apiVersion: v1
kind: Service
metadata:
        name: test-service
spec:
        selector:
                app: testimage
        type: LoadBalancer
        ports:
                - protocol: TCP
                  port: 4400
                  targetPort: 3300
                  nodePort: 30001
        externalIPs: 
                    - 192.168.43.43