apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: ibm-spectrum-scale-csi-lt
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi